# FINALS Data Cleaning <hr style="border:5.5px solid #126782"></hr>

In [4]:
pip install matplotlib



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv(r"..\raw\vgchartz-2024.csv",
                 delimiter=",")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   img           64016 non-null  object 
 1   title         64016 non-null  object 
 2   console       64016 non-null  object 
 3   genre         64016 non-null  object 
 4   publisher     64016 non-null  object 
 5   developer     63999 non-null  object 
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object 
 13  last_update   17879 non-null  object 
dtypes: float64(6), object(8)
memory usage: 6.8+ MB


In [8]:
df = df.drop('img', axis=1)

In [10]:
df[df.isna().any(axis=1)]

title console         genre  \
0                    Grand Theft Auto V     PS3        Action   
2           Grand Theft Auto: Vice City     PS2        Action   
3                    Grand Theft Auto V    X360        Action   
5        Call of Duty: Modern Warfare 3    X360       Shooter   
6               Call of Duty: Black Ops    X360       Shooter   
...                                 ...     ...           ...   
64011             XBlaze Lost: Memories      PC  Visual Novel   
64012                      Yoru, Tomosu     PS4  Visual Novel   
64013                      Yoru, Tomosu      NS  Visual Novel   
64014   Yunohana SpRING! ~Mellow Times~      NS  Visual Novel   
64015  Yurukill: The Calumniation Games     PS4  Visual Novel   

                  publisher             developer  critic_score  total_sales  \
0            Rockstar Games        Rockstar North           9.4        20.32   
2            Rockstar Games        Rockstar North           9.6        16.15   
3            Rockstar Games        Rockstar North           NaN        15.86   
5                Activision         Infinity Ward           8.7        14.82   
6                Activision              Treyarch           8.8        14.74   
...                     ...                   ...           ...          ...   
64011           Aksys Games      Arc System Works           NaN          NaN   
64012  Nippon Ichi Software  Nippon Ichi Software           NaN          NaN   
64013  Nippon Ichi Software  Nippon Ichi Software           NaN          NaN   
64014          Idea Factory               Otomate           NaN          NaN   
64015               Unknown            G.rev Ltd.           NaN          NaN   

       na_sales  jp_sales  pal_sales  other_sales release_date last_update  
0          6.37      0.99       9.85         3.12   2013-09-17         NaN  
2          8.41      0.47       5.49         1.78   2002-10-28         NaN  
3          9.06      0.06       5.33         1.42   2013-09-17         NaN  
5          9.07      0.13       4.29         1.33   2011-11-08         NaN  
6          9.76      0.11       3.73         1.14   2010-11-09         NaN  
...         ...       ...        ...          ...          ...         ...  
64011       NaN       NaN        NaN          NaN   2016-08-11  2019-01-28  
64012       NaN       NaN        NaN          NaN   2020-07-30  2020-05-09  
64013       NaN       NaN        NaN          NaN   2020-07-30  2020-05-09  
64014       NaN       NaN        NaN          NaN   2019-02-28  2019-02-24  
64015       NaN       NaN        NaN          NaN          NaN  2023-09-29  

[63734 rows x 13 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         64016 non-null  object 
 1   console       64016 non-null  object 
 2   genre         64016 non-null  object 
 3   publisher     64016 non-null  object 
 4   developer     63999 non-null  object 
 5   critic_score  6678 non-null   float64
 6   total_sales   18922 non-null  float64
 7   na_sales      12637 non-null  float64
 8   jp_sales      6726 non-null   float64
 9   pal_sales     12824 non-null  float64
 10  other_sales   15128 non-null  float64
 11  release_date  56965 non-null  object 
 12  last_update   17879 non-null  object 
dtypes: float64(6), object(7)
memory usage: 6.3+ MB


In [12]:
df.head()

title console    genre       publisher  \
0           Grand Theft Auto V     PS3   Action  Rockstar Games   
1           Grand Theft Auto V     PS4   Action  Rockstar Games   
2  Grand Theft Auto: Vice City     PS2   Action  Rockstar Games   
3           Grand Theft Auto V    X360   Action  Rockstar Games   
4    Call of Duty: Black Ops 3     PS4  Shooter      Activision   

        developer  critic_score  total_sales  na_sales  jp_sales  pal_sales  \
0  Rockstar North           9.4        20.32      6.37      0.99       9.85   
1  Rockstar North           9.7        19.39      6.06      0.60       9.71   
2  Rockstar North           9.6        16.15      8.41      0.47       5.49   
3  Rockstar North           NaN        15.86      9.06      0.06       5.33   
4        Treyarch           8.1        15.09      6.18      0.41       6.05   

   other_sales release_date last_update  
0         3.12   2013-09-17         NaN  
1         3.02   2014-11-18  2018-01-03  
2         1.78   2002-10-28         NaN  
3         1.42   2013-09-17         NaN  
4         2.44   2015-11-06  2018-01-14

In [13]:
df.describe()

critic_score   total_sales      na_sales     jp_sales     pal_sales  \
count   6678.000000  18922.000000  12637.000000  6726.000000  12824.000000   
mean       7.220440      0.349113      0.264740     0.102281      0.149472   
std        1.457066      0.807462      0.494787     0.168811      0.392653   
min        1.000000      0.000000      0.000000     0.000000      0.000000   
25%        6.400000      0.030000      0.050000     0.020000      0.010000   
50%        7.500000      0.120000      0.120000     0.040000      0.040000   
75%        8.300000      0.340000      0.280000     0.120000      0.140000   
max       10.000000     20.320000      9.760000     2.130000      9.850000   

        other_sales  
count  15128.000000  
mean       0.043041  
std        0.126643  
min        0.000000  
25%        0.000000  
50%        0.010000  
75%        0.030000  
max        3.120000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         64016 non-null  object 
 1   console       64016 non-null  object 
 2   genre         64016 non-null  object 
 3   publisher     64016 non-null  object 
 4   developer     63999 non-null  object 
 5   critic_score  6678 non-null   float64
 6   total_sales   18922 non-null  float64
 7   na_sales      12637 non-null  float64
 8   jp_sales      6726 non-null   float64
 9   pal_sales     12824 non-null  float64
 10  other_sales   15128 non-null  float64
 11  release_date  56965 non-null  object 
 12  last_update   17879 non-null  object 
dtypes: float64(6), object(7)
memory usage: 6.3+ MB


# Determining **District** Values

In [22]:
df['title'].unique()

array(['Grand Theft Auto V', 'Grand Theft Auto: Vice City',
       'Call of Duty: Black Ops 3', ..., 'Yoru, Tomosu',
       'Yunohana SpRING! ~Mellow Times~',
       'Yurukill: The Calumniation Games'], shape=(39798,), dtype=object)

In [23]:
df['title'].nunique()


39798

In [24]:
df['console'].unique()

array(['PS3', 'PS4', 'PS2', 'X360', 'XOne', 'PC', 'PSP', 'Wii', 'PS',
       'DS', '2600', 'GBA', 'NES', 'XB', 'PSN', 'GEN', 'PSV', 'DC', 'N64',
       'SAT', 'SNES', 'GBC', 'GC', 'NS', '3DS', 'GB', 'WiiU', 'WS', 'VC',
       'NG', 'WW', 'SCD', 'PCE', 'XBL', '3DO', 'GG', 'OSX', 'Mob', 'PCFX',
       'Series', 'All', 'iOS', '5200', 'And', 'DSiW', 'Lynx', 'Linux',
       'MS', 'ZXS', 'ACPC', 'Amig', '7800', 'DSi', 'AJ', 'WinP', 'iQue',
       'GIZ', 'VB', 'Ouya', 'NGage', 'AST', 'MSD', 'S32X', 'XS', 'PS5',
       'Int', 'CV', 'Arc', 'C64', 'FDS', 'MSX', 'OR', 'C128', 'CDi',
       'CD32', 'BRW', 'FMT', 'ApII', 'Aco', 'BBCM', 'TG16'], dtype=object)

In [25]:
df['console'].nunique()

81

In [26]:
df['genre'].unique()

array(['Action', 'Shooter', 'Action-Adventure', 'Sports', 'Role-Playing',
       'Simulation', 'Racing', 'Music', 'Misc', 'Fighting', 'Platform',
       'Adventure', 'Strategy', 'Puzzle', 'MMO', 'Sandbox', 'Party',
       'Education', 'Board Game', 'Visual Novel'], dtype=object)

In [27]:
df['genre'].nunique()

20

In [28]:
df['publisher'].unique()

array(['Rockstar Games', 'Activision', 'EA Sports', ...,
       "Mind's Eclipse Interactive", 'Walkabout', 'InvertMouse'],
      shape=(3383,), dtype=object)

In [29]:
df['publisher'].nunique()

3383

In [30]:
df['developer'].unique()

array(['Rockstar North', 'Treyarch', 'Infinity Ward', ...,
       'Different Tales', '4D Door Games', 'InvertMouse'],
      shape=(8863,), dtype=object)

In [31]:
df['developer'].nunique()

8862

In [32]:
df['critic_score'].unique()

array([ 9.4,  9.7,  9.6,  nan,  8.1,  8.7,  8.8,  9.8,  8.4,  8. ,  9.5,
        8.3, 10. ,  8.9,  6.9,  7.5,  9.3,  9. ,  7.9,  8.6,  8.5,  7.1,
        9.1,  9.2,  6.6,  8.2,  7.6,  5.9,  7. ,  7.8,  7.7,  6.8,  5.6,
        4.2,  7.4,  7.3,  6.7,  7.2,  6.1,  6.2,  3.5,  3. ,  3.6,  6.5,
        2.6,  6. ,  5.5,  5.8,  4.8,  5.4,  6.3,  6.4,  4.4,  3.2,  5. ,
        3.8,  5.1,  4.3,  4.5,  4.9,  5.3,  4.6,  5.7,  2.9,  4.7,  1.7,
        4.1,  4. ,  3.9,  5.2,  3.7,  2.8,  3.1,  3.3,  1.9,  2.5,  2.4,
        2. ,  2.7,  3.4,  2.3,  1.5,  1. ,  2.2,  1.4,  1.3,  9.9,  1.2,
        1.8,  2.1])

In [33]:
df['critic_score'].nunique()

89

In [34]:
df['total_sales'].unique()

array([2.032e+01, 1.939e+01, 1.615e+01, 1.586e+01, 1.509e+01, 1.482e+01,
       1.474e+01, 1.394e+01, 1.386e+01, 1.380e+01, 1.353e+01, 1.340e+01,
       1.335e+01, 1.310e+01, 1.267e+01, 1.180e+01, 1.109e+01, 1.094e+01,
       1.061e+01, 1.057e+01, 1.041e+01, 1.013e+01, 9.970e+00, 9.960e+00,
       9.410e+00, 9.320e+00, 9.150e+00, 8.880e+00, 8.720e+00, 8.480e+00,
       8.220e+00, 8.030e+00, 8.010e+00, 7.960e+00, 7.720e+00, 7.530e+00,
       7.500e+00, 7.370e+00, 7.350e+00, 7.260e+00, 7.210e+00, 7.200e+00,
       6.900e+00, 6.890e+00, 6.830e+00, 6.740e+00, 6.720e+00, 6.650e+00,
       6.610e+00, 6.570e+00, 6.500e+00, 6.490e+00, 6.330e+00, 6.320e+00,
       6.270e+00, 6.230e+00, 6.050e+00, 5.770e+00, 5.760e+00, 5.740e+00,
       5.660e+00, 5.570e+00, 5.550e+00, 5.540e+00, 5.500e+00, 5.430e+00,
       5.420e+00, 5.350e+00, 5.310e+00, 5.300e+00, 5.240e+00, 5.230e+00,
       5.220e+00, 5.130e+00, 5.120e+00, 5.110e+00, 5.100e+00, 5.080e+00,
       5.070e+00, 5.030e+00, 5.020e+00, 5.010e+00, 

In [35]:
df['total_sales'].nunique()

482

In [36]:
df['na_sales'].unique()

array([6.37, 6.06, 8.41, 9.06, 6.18, 9.07, 9.76, 5.26, 8.27, 4.99, 8.54,
       4.67, 5.54, 6.99, 6.01, 1.27, 6.8 , 1.26, 4.79, 6.76, 4.11, 7.08,
       6.72, 5.98, 4.05, 0.84, 5.1 , 4.7 , 3.11, 2.91, 1.15, 3.31, 1.07,
       1.01, 2.9 , 2.84, 4.88, 4.63, 4.47, 2.2 , 2.86, 3.27, 2.71, 2.93,
       3.28, 3.13, 0.79, 2.82, 3.77, 2.65, 2.57, 1.89, 0.83, 3.75, 2.21,
       3.76, 2.53, 2.26, 3.57, 3.09, 2.54, 2.72, 2.99, 2.75, 3.23, 2.07,
       1.75, 3.14, 2.3 , 4.26, 3.25, 1.98, 3.37, 3.22, 3.81, 1.1 , 1.63,
       3.59, 1.96, 0.61, 1.7 , 1.81, 2.94, 3.42, 2.79, 3.49, 2.32, 3.41,
       3.98, 1.91, 1.09, 2.83, 2.36, 1.73, 3.05, 1.94, 2.29, 2.08, 3.04,
       0.59, 1.87, 1.84, 3.19, 4.18, 2.89, 2.66, 0.1 , 1.49, 2.03, 2.64,
       1.29, 2.81, 1.4 , 4.  , 1.59, 3.  , 1.41, 2.28, 0.78, 2.04, 0.85,
       1.79, 3.38, 3.79, 0.94, 2.49, 3.36, 1.25, 1.92, 0.71, 1.65, 1.2 ,
       2.67, 2.12, 1.18, 1.22, 0.12, 2.35, 1.68, 2.18, 2.56, 1.44, 1.34,
       2.15, 0.16, 2.4 , 1.04, 0.58, 2.13, 1.58, 1.

In [37]:
df['na_sales'].nunique()

320

In [38]:
df['jp_sales'].unique()

array([0.99, 0.6 , 0.47, 0.06, 0.41, 0.13, 0.11, 0.21, 0.07, 0.65, 0.08,
       0.4 , 0.49, 0.3 , 0.48, 0.15, 0.14, 0.12, 0.38, 0.44, 0.04, 0.39,
       0.5 , 0.1 , 0.01, 0.19, 0.27, 0.23,  nan, 0.24, 0.02, 0.29, 0.35,
       0.17, 0.28, 0.09, 0.16, 0.25, 0.05, 1.36, 1.87, 0.03, 0.2 , 1.08,
       1.05, 0.  , 0.22, 0.36, 0.59, 0.31, 0.9 , 0.51, 1.12, 0.64, 0.33,
       0.88, 1.16, 1.38, 2.13, 0.89, 0.26, 0.18, 1.25, 0.46, 0.54, 2.05,
       0.55, 0.96, 0.79, 1.43, 0.63, 1.3 , 0.52, 1.48, 0.42, 1.82, 0.72,
       0.53, 1.34, 1.69, 0.32, 0.34, 1.27, 1.5 , 1.44, 1.45, 1.39, 1.  ,
       1.26, 0.85, 1.1 , 0.75, 0.62, 1.2 , 1.18, 0.83, 0.77, 0.43, 1.07,
       1.15, 0.76, 1.06, 0.45, 0.71, 1.04, 0.92, 0.37, 0.74, 0.57, 0.66,
       0.91, 0.87, 0.81, 0.8 , 0.78, 0.73, 0.61, 0.67, 0.7 , 0.58, 0.69,
       0.56])

In [39]:
df['jp_sales'].nunique()

121

In [40]:
df['pal_sales'].unique()

array([9.85, 9.71, 5.49, 5.33, 6.05, 4.29, 3.73, 6.21, 4.32, 5.88, 3.63,
       5.78, 4.51, 4.4 , 8.64, 3.11, 7.95, 3.66, 2.64, 4.01, 2.01, 2.36,
       2.39, 3.28, 6.87, 2.83, 3.25, 3.83, 3.97, 5.77, 3.19, 5.13, 6.46,
       3.34, 1.91, 2.04, 2.12, 3.65, 2.94, 3.02, 2.21, 2.75, 2.22, 2.27,
       4.33, 4.77, 2.58, 2.03, 2.61, 2.68, 3.13, 4.49, 2.8 , 2.86, 1.47,
       2.13, 1.89, 1.57, 1.92, 1.95, 1.64, 1.9 , 1.84, 1.71, 2.29, 1.23,
       1.55, 2.46, 0.26, 1.49, 2.23, 1.26, 1.69, 0.63, 3.49, 1.09, 1.42,
       1.53, 1.62, 1.38, 0.01, 1.73, 0.99, 1.12, 2.92, 1.44, 1.28, 2.1 ,
       2.19, 1.41, 1.97, 1.98, 1.8 , 0.91, 1.99, 1.51, 1.03, 1.29, 1.79,
       1.33, 2.06, 1.13, 1.81, 1.11, 2.55, 1.05, 2.79, 0.44, 0.27, 0.21,
       2.16, 2.48, 1.68, 2.6 , 2.14, 2.11, 2.26, 1.27, 1.15, 2.25, 0.66,
       1.35, 1.74, 1.86, 1.17, 1.66, 1.01, 1.56, 1.4 , 2.4 , 1.18, 1.6 ,
       1.22, 0.81, 1.5 , 0.  , 0.96, 1.02, 0.9 , 1.77, 1.58, 0.95, 0.93,
       0.39, 1.14, 0.59, 0.94, 0.72, 1.63, 1.04, 1.

In [41]:
df['pal_sales'].nunique()

256

In [42]:
df['other_sales'].unique()

array([3.12, 3.02, 1.78, 1.42, 2.44, 1.33, 1.14, 2.26, 1.2 , 2.28, 1.28,
       2.12, 1.54, 1.3 , 1.73, 1.04, 1.61, 1.59, 1.62, 0.98, 0.8 , 0.83,
       0.91, 1.49, 1.34, 0.85, 0.76, 1.36, 1.23, 1.68, 0.5 , 1.74, 1.22,
       0.71, 0.68, 0.69, 1.12, 1.07, 1.02, 1.09, 0.62, 0.99, 1.37, 1.  ,
       0.6 , 1.08, 0.96, 0.94, 0.33, 0.57, 0.54, 0.23, 0.52, 0.58, 0.86,
       0.56, 0.82, 0.51, 0.84, 0.49, 0.45, 0.28, 0.48, 0.2 , 0.37, 0.64,
       1.19, 1.48, 0.46, 0.66, 0.74, 0.44, 0.21, 0.25, 0.79, 0.7 , 0.24,
       0.73, 0.42, 0.08, 0.41, 0.47, 0.39, 0.05, 0.63, 0.67, 0.07, 0.04,
       0.11, 0.29, 0.38, 0.65, 0.89, 0.3 , 0.34, 0.77, 0.06, 0.35, 0.61,
       0.36, 0.17, 0.27, 0.59, 0.4 , 0.55, 2.93, 0.16, 0.18, 0.32, 0.31,
       0.22, 0.43, 0.13, 0.19, 2.46, 0.14, 0.26, 1.16, 0.09,  nan, 2.05,
       0.15, 0.1 , 0.02, 1.41, 1.82, 0.03, 0.12, 0.01, 1.13, 0.  , 0.93,
       0.75, 0.53])

In [43]:
df['other_sales'].nunique()

133

In [45]:
df['release_date'].unique()

array(['2013-09-17', '2014-11-18', '2002-10-28', ..., '2018-04-02',
       '2021-03-24', '2016-08-11'], shape=(7923,), dtype=object)

In [46]:
df['release_date'].nunique()

7922

In [47]:
df['last_update'].unique()

array([nan, '2018-01-03', '2018-01-14', ..., '2020-05-03', '2021-04-13',
       '2023-04-13'], shape=(1546,), dtype=object)

In [48]:
df['last_update'].nunique()

1545

# Data Cleaning

<h2> Dropping NaN </h2>

In [51]:
df.isna().sum()


title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [52]:
df_c = df.copy()

In [ ]:
# Cleaning developer column
df_c = df_c.dropna(subset=['developer'])
df_c.isna().sum()

title               0
console             0
genre               0
publisher           0
developer           0
critic_score    57321
total_sales     45081
na_sales        51364
jp_sales        57273
pal_sales       51178
other_sales     48874
release_date     7045
last_update     46122
dtype: int64

In [55]:
# Cleaning critic_score column
df_c = df_c.dropna(subset=['critic_score'])
df_c.isna().sum()

title              0
console            0
genre              0
publisher          0
developer          0
critic_score       0
total_sales     2552
na_sales        2940
jp_sales        5276
pal_sales       2899
other_sales     2675
release_date      44
last_update     5708
dtype: int64

In [64]:
# Cleaning total_sales column
df_c = df_c.dropna(subset=['total_sales'])
df_c.isna().sum()

title              0
console            0
genre              0
publisher          0
developer          0
critic_score       0
total_sales        0
na_sales         388
jp_sales        2724
pal_sales        347
other_sales      123
release_date       3
last_update     3524
dtype: int64

In [65]:
# Cleaning na_sales column
df_c = df_c.dropna(subset=['na_sales'])
df_c.isna().sum()

title              0
console            0
genre              0
publisher          0
developer          0
critic_score       0
total_sales        0
na_sales           0
jp_sales        2461
pal_sales        247
other_sales       31
release_date       0
last_update     3200
dtype: int64

In [66]:
# Cleaning jp_sales column
df_c = df_c.dropna(subset=['jp_sales'])
df_c.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales        62
other_sales       6
release_date      0
last_update     978
dtype: int64

In [67]:
# Cleaning pal_sales column
df_c = df_c.dropna(subset=['pal_sales'])
df_c.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales         0
other_sales       5
release_date      0
last_update     933
dtype: int64

In [68]:
# Cleaning other_sales column
df_c = df_c.dropna(subset=['other_sales'])
df_c.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales         0
other_sales       0
release_date      0
last_update     928
dtype: int64

<h2> Replacing NaN with Mean </h2>

In [105]:
df_m = df_c.copy()

In [106]:
df_m.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales         0
other_sales       0
release_date      0
last_update     928
dtype: int64

In [107]:
# Cleaning critic_score column with mean
dev_mean = df_m['critic_score'].mean()
print(dev_mean)
df_m['critic_score'] = df_m['critic_score'].fillna(dev_mean)

7.537768595041323


In [108]:
# Cleaning total_sales column with mean
df_m['total_sales'] = df_m['total_sales'].fillna(df_m['total_sales'].mean())
print(df_m['total_sales'].mean().round(4))

1.4998


In [109]:
# Cleaning na_sales column with mean
df_m['na_sales'] = df_m['na_sales'].fillna(df_m['na_sales'].mean())
print(df_m['na_sales'].mean().round(4))

0.6904


In [110]:
# Cleaning jp_sales column with mean
df_m['jp_sales'] = df_m['jp_sales'].fillna(df_m['jp_sales'].mean())
print(df_m['jp_sales'].mean().round(4))

0.1065


In [111]:
# Cleaning pal_sales column with mean
df_m['pal_sales'] = df_m['pal_sales'].fillna(df_m['pal_sales'].mean())
print(df_m['pal_sales'].mean().round(4))

0.5247


In [112]:
# Cleaning other_sales column with mean
df_m['other_sales'] = df_m['other_sales'].fillna(df_m['other_sales'].mean())
print(df_m['other_sales'].mean().round(4))

0.1781


In [113]:
df_m.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales         0
other_sales       0
release_date      0
last_update     928
dtype: int64

In [114]:
df_m.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1210 entries, 0 to 15044
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         1210 non-null   object 
 1   console       1210 non-null   object 
 2   genre         1210 non-null   object 
 3   publisher     1210 non-null   object 
 4   developer     1210 non-null   object 
 5   critic_score  1210 non-null   float64
 6   total_sales   1210 non-null   float64
 7   na_sales      1210 non-null   float64
 8   jp_sales      1210 non-null   float64
 9   pal_sales     1210 non-null   float64
 10  other_sales   1210 non-null   float64
 11  release_date  1210 non-null   object 
 12  last_update   282 non-null    object 
dtypes: float64(6), object(7)
memory usage: 132.3+ KB


In [116]:
df_m.describe()

critic_score  total_sales     na_sales     jp_sales    pal_sales  \
count   1210.000000  1210.000000  1210.000000  1210.000000  1210.000000   
mean       7.537769     1.499777     0.690438     0.106512     0.524727   
std        1.200153     2.228479     1.097869     0.164748     0.953987   
min        3.000000     0.020000     0.010000     0.000000     0.000000   
25%        6.800000     0.350000     0.140000     0.020000     0.050000   
50%        7.700000     0.710000     0.290000     0.050000     0.200000   
75%        8.400000     1.577500     0.727500     0.127500     0.530000   
max       10.000000    20.320000     9.760000     1.870000     9.850000   

       other_sales  
count  1210.000000  
mean      0.178074  
std       0.322764  
min       0.000000  
25%       0.020000  
50%       0.060000  
75%       0.180000  
max       3.120000

In [118]:
df_m.isna().sum()

title             0
console           0
genre             0
publisher         0
developer         0
critic_score      0
total_sales       0
na_sales          0
jp_sales          0
pal_sales         0
other_sales       0
release_date      0
last_update     928
dtype: int64

In [119]:
df_m.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1210 entries, 0 to 15044
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         1210 non-null   object 
 1   console       1210 non-null   object 
 2   genre         1210 non-null   object 
 3   publisher     1210 non-null   object 
 4   developer     1210 non-null   object 
 5   critic_score  1210 non-null   float64
 6   total_sales   1210 non-null   float64
 7   na_sales      1210 non-null   float64
 8   jp_sales      1210 non-null   float64
 9   pal_sales     1210 non-null   float64
 10  other_sales   1210 non-null   float64
 11  release_date  1210 non-null   object 
 12  last_update   282 non-null    object 
dtypes: float64(6), object(7)
memory usage: 132.3+ KB


# **Saving** the Cleaned Dataset

In [120]:
df_m.to_csv(r"..\raw\vgchartz-2024-cleansed.csv", index=False)